// Code generated by "pipeline"; DO NOT EDIT.
package linnea

import (
	_ "embed"

	"fmt"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
	"slices"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	1: {"recast"},
	3: {"travel"},
	7: {"hold", "travel", "weakspot"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Linnea, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][]float64{
		attack_1,
		attack_2,
		attack_3,
	}
)

var (
	// attack: aim = [3]
	aim = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.9282,
		0.9894,
		1.0506,
		1.1118,
		1.173,
	}
	// attack: attack_1 = [0]
	attack_1 = []float64{
		0.589969,
		0.637989,
		0.68601,
		0.754611,
		0.802632,
		0.857513,
		0.932974,
		1.008435,
		1.083896,
		1.166217,
		1.248538,
		1.330859,
		1.413181,
		1.495502,
		1.577823,
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
		0.511519,
		0.553155,
		0.59479,
		0.654269,
		0.695904,
		0.743488,
		0.808914,
		0.874341,
		0.939768,
		1.011143,
		1.082518,
		1.153893,
		1.225267,
		1.296642,
		1.368017,
	}
	// attack: attack_3 = [3]
	attack_3 = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.9282,
		0.9894,
		1.0506,
		1.1118,
		1.173,
	}
	// attack: collision = [4]
	collision = []float64{
		1.24,
		1.333,
		1.426,
		1.55,
		1.643,
		1.736,
		1.86,
		1.984,
		2.108,
		2.232,
		2.356,
		2.48,
		2.635,
		2.79,
		2.945,
	}
	// attack: highPlunge = [6]
	highPlunge = []float64{
		1.136335,
		1.228828,
		1.32132,
		1.453452,
		1.545944,
		1.65165,
		1.796995,
		1.94234,
		2.087686,
		2.246244,
		2.404802,
		2.563361,
		2.721919,
		2.880478,
		3.039036,
	}
	// attack: lowPlunge = [5]
	lowPlunge = []float64{
		0.568288,
		0.614544,
		0.6608,
		0.72688,
		0.773136,
		0.826,
		0.898688,
		0.971376,
		1.044064,
		1.12336,
		1.202656,
		1.281952,
		1.361248,
		1.440544,
		1.51984,
	}
	// skill: skillBig = [2]
	skillBig = []float64{
		4,
		4.3,
		4.6,
		5,
		5.3,
		5.6,
		6,
		6.4,
		6.8,
		7.2,
		7.6,
		8,
		8.5,
		9,
		9.5,
	}
	// skill: skillCooldown = [4]
	skillCooldown = []float64{
		18,
		18,
		18,
		18,
		18,
		18,
		18,
		18,
		18,
		18,
		18,
		18,
		18,
		18,
		18,
	}
	// skill: skillDuration = [3]
	skillDuration = []float64{
		25,
		25,
		25,
		25,
		25,
		25,
		25,
		25,
		25,
		25,
		25,
		25,
		25,
		25,
		25,
	}
	// skill: skillTurret = [0]
	skillTurret = []float64{
		0.96,
		1.032,
		1.104,
		1.2,
		1.272,
		1.344,
		1.44,
		1.536,
		1.632,
		1.728,
		1.824,
		1.92,
		2.04,
		2.16,
		2.28,
	}
	// skill: skillTurretLunar = [1]
	skillTurretLunar = []float64{
		1,
		1.075,
		1.15,
		1.25,
		1.325,
		1.4,
		1.5,
		1.6,
		1.7,
		1.8,
		1.9,
		2,
		2.125,
		2.25,
		2.375,
	}
	// burst: burstCooldown = [5]
	burstCooldown = []float64{
		15,
		15,
		15,
		15,
		15,
		15,
		15,
		15,
		15,
		15,
		15,
		15,
		15,
		15,
		15,
	}
	// burst: burstDuration = [4]
	burstDuration = []float64{
		12,
		12,
		12,
		12,
		12,
		12,
		12,
		12,
		12,
		12,
		12,
		12,
		12,
		12,
		12,
	}
	// burst: burstEnergyCost = [6]
	burstEnergyCost = []float64{
		60,
		60,
		60,
		60,
		60,
		60,
		60,
		60,
		60,
		60,
		60,
		60,
		60,
		60,
		60,
	}
	// burst: burstHealBig = [1]
	burstHealBig = []float64{
		1.6,
		1.72,
		1.84,
		2,
		2.12,
		2.24,
		2.4,
		2.56,
		2.72,
		2.88,
		3.04,
		3.2,
		3.4,
		3.6,
		3.8,
	}
	// burst: burstHealBigAdditive = [0]
	burstHealBigAdditive = []float64{
		770.3755,
		847.42377,
		930.8927,
		1020.78235,
		1117.0927,
		1219.8236,
		1328.9753,
		1444.5477,
		1566.5408,
		1694.9546,
		1829.7891,
		1971.0442,
		2118.72,
		2272.8164,
		2433.3337,
	}
	// burst: burstHealContinuous = [3]
	burstHealContinuous = []float64{
		0.32,
		0.344,
		0.368,
		0.4,
		0.424,
		0.448,
		0.48,
		0.512,
		0.544,
		0.576,
		0.608,
		0.64,
		0.68,
		0.72,
		0.76,
	}
	// burst: burstHealContinuousAdditive = [2]
	burstHealContinuousAdditive = []float64{
		154.0751,
		169.48476,
		186.17854,
		204.15646,
		223.41853,
		243.96474,
		265.79507,
		288.90955,
		313.30817,
		338.9909,
		365.9578,
		394.20883,
		423.744,
		454.5633,
		486.66675,
	}
)
